#!/usr/bin/env python3
"""Generate compose.fleet.yaml + Caddyfile from towns.json.

towns.json is the single source of truth for the fleet (which towns exist, their
subdomains, and which DB each uses). Secrets (image tag, SMTP creds, MySQL root
password, per-town DB passwords) are NOT baked in here -- the generated compose
references them as ${VAR}, resolved at runtime from the sibling .env via docker
compose interpolation. So this script needs no secrets and is safe to run anywhere.

Run:  python3 generate.py
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
cfg = json.loads((HERE / "towns.json").read_text())
base = cfg["domainBase"]
acme = cfg.get("acmeEmail", "")
towns = cfg["towns"]


def ghost_service(t):
    slug = t["slug"]
    sub = t.get("subdomain", slug)
    name = t["name"]
    db = t.get("dbName", f"ghost_{slug}")
    user = t.get("dbUser", f"ghost_{slug}")
    return f"""  ghost-{slug}:
    image: ${{GHOST_IMAGE}}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      NODE_ENV: production
      url: https://{sub}.{base}
      server__host: "0.0.0.0"
      server__port: "2368"
      security__staffDeviceVerification: "false"
      database__client: mysql
      database__connection__host: mysql
      database__connection__database: {db}
      database__connection__user: {user}
      database__connection__password: ${{DBPASS_{slug}}}
      mail__transport: SMTP
      mail__from: "{name} <newsletter@{base}>"
      mail__options__host: ${{SMTP_HOST}}
      mail__options__port: ${{SMTP_PORT}}
      mail__options__auth__user: ${{SMTP_USER}}
      mail__options__auth__pass: ${{SMTP_PASS}}
    volumes:
      - ghost-content-{slug}:/home/ghost/content
"""


depends = "".join(f"      - ghost-{t['slug']}\n" for t in towns)
services = "".join(ghost_service(t) for t in towns)
volumes = ("  mysql-data:\n  caddy-data:\n  caddy-config:\n"
           + "".join(f"  ghost-content-{t['slug']}:\n" for t in towns))

compose = f"""# GENERATED by generate.py from towns.json -- DO NOT EDIT BY HAND.
# Regenerate after editing towns.json:  python3 generate.py
services:
  mysql:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${{MYSQL_ROOT_PASSWORD}}
    command: ["--innodb-buffer-pool-size=512M"]
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10

  caddy:
    image: caddy:2
    restart: always
    depends_on:
{depends}    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

{services}
volumes:
{volumes}"""

(HERE / "compose.fleet.yaml").write_text(compose)

global_block = (f"{{\n\temail {acme}\n}}\n\n" if acme else "")
sites = "".join(
    f"{t.get('subdomain', t['slug'])}.{base} {{\n"
    f"\treverse_proxy ghost-{t['slug']}:2368\n"
    f"\tencode gzip\n}}\n\n"
    for t in towns
)
(HERE / "Caddyfile").write_text(
    "# GENERATED by generate.py -- DO NOT EDIT BY HAND.\n" + global_block + sites)

print("generated compose.fleet.yaml + Caddyfile for %d town(s): %s"
      % (len(towns), ", ".join(t["slug"] for t in towns)))
